# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cyp',
            fields=[
                ('cypcod', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cypnom', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Lng',
            fields=[
                ('lngcod', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('lngnom', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='cyp',
            name='cyplngcod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.Lng'),
        ),
    ]
