# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170425_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cyp',
            name='cyplngcod',
        ),
    ]
