# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_cyp_cyplngcod'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyp',
            name='cypobs',
            field=models.CharField(default='', max_length=80, verbose_name='Esto es un campo de observaciones'),
        ),
    ]
