# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_cyp_cypobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyp',
            name='cypobs',
            field=models.CharField(default='', max_length=80),
        ),
    ]
