# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170425_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('regcod', models.BigIntegerField(primary_key=True, serialize=False)),
                ('regkey', models.CharField(max_length=80, unique=True)),
                ('regtxt', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ser',
            fields=[
                ('sercod', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('serval', models.BigIntegerField(default=0)),
            ],
        ),
    ]
