package org.cargo.bl.jpa;
// Generated 23-abr-2016 20:32:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Cto generated by hbm2java
 */
@Entity
@Table(name="cto"
    ,catalog="cargo"
)
public class Cto  implements java.io.Serializable {


     private String ctocod;
     private long version;
     private String ctodes;
     private short ctoest;

    public Cto() {
    }

    public Cto(String ctocod, String ctodes, short ctoest) {
       this.ctocod = ctocod;
       this.ctodes = ctodes;
       this.ctoest = ctoest;
    }
   
     @Id 

    
    @Column(name="ctocod", unique=true, nullable=false, length=5)
    public String getCtocod() {
        return this.ctocod;
    }
    
    public void setCtocod(String ctocod) {
        this.ctocod = ctocod;
    }

    @Version
    @Column(name="version", nullable=false)
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }

    
    @Column(name="ctodes", nullable=false, length=80)
    public String getCtodes() {
        return this.ctodes;
    }
    
    public void setCtodes(String ctodes) {
        this.ctodes = ctodes;
    }

    
    @Column(name="ctoest", nullable=false)
    public short getCtoest() {
        return this.ctoest;
    }
    
    public void setCtoest(short ctoest) {
        this.ctoest = ctoest;
    }




}


