package org.cargo.bl.jpa;
// Generated 23-abr-2016 18:56:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Cyp generated by hbm2java
 */
@Entity
@Table(name="cyp"
    ,catalog="cargo"
)
public class Cyp  implements java.io.Serializable {


     private long cypcod;
     private long version;
     private String cypraz;
     private String cypidf;
     private String cyptkr;
     private Set<Tta> ttas = new HashSet<Tta>(0);
     private Set<Tca> tcas = new HashSet<Tca>(0);

    public Cyp() {
    }

	
    public Cyp(long cypcod, String cypraz, String cypidf, String cyptkr) {
        this.cypcod = cypcod;
        this.cypraz = cypraz;
        this.cypidf = cypidf;
        this.cyptkr = cyptkr;
    }
    public Cyp(long cypcod, String cypraz, String cypidf, String cyptkr, Set<Tta> ttas, Set<Tca> tcas) {
       this.cypcod = cypcod;
       this.cypraz = cypraz;
       this.cypidf = cypidf;
       this.cyptkr = cyptkr;
       this.ttas = ttas;
       this.tcas = tcas;
    }
   
     @Id 

    
    @Column(name="cypcod", unique=true, nullable=false)
    public long getCypcod() {
        return this.cypcod;
    }
    
    public void setCypcod(long cypcod) {
        this.cypcod = cypcod;
    }

    @Version
    @Column(name="version", nullable=false)
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }

    
    @Column(name="cypraz", nullable=false, length=80)
    public String getCypraz() {
        return this.cypraz;
    }
    
    public void setCypraz(String cypraz) {
        this.cypraz = cypraz;
    }

    
    @Column(name="cypidf", nullable=false, length=20)
    public String getCypidf() {
        return this.cypidf;
    }
    
    public void setCypidf(String cypidf) {
        this.cypidf = cypidf;
    }

    
    @Column(name="cyptkr", nullable=false, length=5)
    public String getCyptkr() {
        return this.cyptkr;
    }
    
    public void setCyptkr(String cyptkr) {
        this.cyptkr = cyptkr;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cyp")
    public Set<Tta> getTtas() {
        return this.ttas;
    }
    
    public void setTtas(Set<Tta> ttas) {
        this.ttas = ttas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cyp")
    public Set<Tca> getTcas() {
        return this.tcas;
    }
    
    public void setTcas(Set<Tca> tcas) {
        this.tcas = tcas;
    }




}


