package org.cargo.bl.jpa;
// Generated 23-abr-2016 20:32:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Emp generated by hbm2java
 */
@Entity
@Table(name="emp"
    ,catalog="cargo"
)
public class Emp  implements java.io.Serializable {


     private long empcod;
     private long version;
     private String empraz;
     private String empidf;
     private String emptkr;

    public Emp() {
    }

    public Emp(long empcod, String empraz, String empidf, String emptkr) {
       this.empcod = empcod;
       this.empraz = empraz;
       this.empidf = empidf;
       this.emptkr = emptkr;
    }
   
     @Id 

    
    @Column(name="empcod", unique=true, nullable=false)
    public long getEmpcod() {
        return this.empcod;
    }
    
    public void setEmpcod(long empcod) {
        this.empcod = empcod;
    }

    @Version
    @Column(name="version", nullable=false)
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }

    
    @Column(name="empraz", nullable=false, length=80)
    public String getEmpraz() {
        return this.empraz;
    }
    
    public void setEmpraz(String empraz) {
        this.empraz = empraz;
    }

    
    @Column(name="empidf", nullable=false, length=20)
    public String getEmpidf() {
        return this.empidf;
    }
    
    public void setEmpidf(String empidf) {
        this.empidf = empidf;
    }

    
    @Column(name="emptkr", nullable=false, length=5)
    public String getEmptkr() {
        return this.emptkr;
    }
    
    public void setEmptkr(String emptkr) {
        this.emptkr = emptkr;
    }




}


