package org.cargo.bl.jpa;
// Generated 23-abr-2016 18:56:39 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Seq generated by hbm2java
 */
@Entity
@Table(name="seq"
    ,catalog="cargo"
)
public class Seq  implements java.io.Serializable {


     private String seqcod;
     private long version;
     private String seqdes;
     private long segnxt;

    public Seq() {
    }

    public Seq(String seqcod, String seqdes, long segnxt) {
       this.seqcod = seqcod;
       this.seqdes = seqdes;
       this.segnxt = segnxt;
    }
   
     @Id 

    
    @Column(name="seqcod", unique=true, nullable=false, length=20)
    public String getSeqcod() {
        return this.seqcod;
    }
    
    public void setSeqcod(String seqcod) {
        this.seqcod = seqcod;
    }

    @Version
    @Column(name="version", nullable=false)
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }

    
    @Column(name="seqdes", nullable=false, length=80)
    public String getSeqdes() {
        return this.seqdes;
    }
    
    public void setSeqdes(String seqdes) {
        this.seqdes = seqdes;
    }

    
    @Column(name="segnxt", nullable=false)
    public long getSegnxt() {
        return this.segnxt;
    }
    
    public void setSegnxt(long segnxt) {
        this.segnxt = segnxt;
    }




}


