package org.cargo.bl.jpa;
// Generated 23-abr-2016 18:56:39 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Tca generated by hbm2java
 */
@Entity
@Table(name="tca"
    ,catalog="cargo"
)
public class Tca  implements java.io.Serializable {


     private long tcacod;
     private long version;
     private Cyp cyp;
     private Teo teo;
     private String tcaloc;
     private String tcacypraz;
     private String tcacypidf;
     private String tcacyptkr;

    public Tca() {
    }

    public Tca(long tcacod, Cyp cyp, Teo teo, String tcaloc, String tcacypraz, String tcacypidf, String tcacyptkr) {
       this.tcacod = tcacod;
       this.cyp = cyp;
       this.teo = teo;
       this.tcaloc = tcaloc;
       this.tcacypraz = tcacypraz;
       this.tcacypidf = tcacypidf;
       this.tcacyptkr = tcacyptkr;
    }
   
     @Id 

    
    @Column(name="tcacod", unique=true, nullable=false)
    public long getTcacod() {
        return this.tcacod;
    }
    
    public void setTcacod(long tcacod) {
        this.tcacod = tcacod;
    }

    @Version
    @Column(name="version", nullable=false)
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tcacypcod", nullable=false)
    public Cyp getCyp() {
        return this.cyp;
    }
    
    public void setCyp(Cyp cyp) {
        this.cyp = cyp;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tcateocod", nullable=false)
    public Teo getTeo() {
        return this.teo;
    }
    
    public void setTeo(Teo teo) {
        this.teo = teo;
    }

    
    @Column(name="tcaloc", nullable=false, length=20)
    public String getTcaloc() {
        return this.tcaloc;
    }
    
    public void setTcaloc(String tcaloc) {
        this.tcaloc = tcaloc;
    }

    
    @Column(name="tcacypraz", nullable=false, length=80)
    public String getTcacypraz() {
        return this.tcacypraz;
    }
    
    public void setTcacypraz(String tcacypraz) {
        this.tcacypraz = tcacypraz;
    }

    
    @Column(name="tcacypidf", nullable=false, length=20)
    public String getTcacypidf() {
        return this.tcacypidf;
    }
    
    public void setTcacypidf(String tcacypidf) {
        this.tcacypidf = tcacypidf;
    }

    
    @Column(name="tcacyptkr", nullable=false, length=5)
    public String getTcacyptkr() {
        return this.tcacyptkr;
    }
    
    public void setTcacyptkr(String tcacyptkr) {
        this.tcacyptkr = tcacyptkr;
    }




}


