package org.cargo.bl.jpa;
// Generated 23-abr-2016 18:56:39 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Tea generated by hbm2java
 */
@Entity
@Table(name="tea"
    ,catalog="cargo"
)
public class Tea  implements java.io.Serializable {


     private String teacod;
     private long version;
     private String teades;
     private short teadef;

    public Tea() {
    }

    public Tea(String teacod, String teades, short teadef) {
       this.teacod = teacod;
       this.teades = teades;
       this.teadef = teadef;
    }
   
     @Id 

    
    @Column(name="teacod", unique=true, nullable=false, length=5)
    public String getTeacod() {
        return this.teacod;
    }
    
    public void setTeacod(String teacod) {
        this.teacod = teacod;
    }

    @Version
    @Column(name="version", nullable=false)
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }

    
    @Column(name="teades", nullable=false, length=80)
    public String getTeades() {
        return this.teades;
    }
    
    public void setTeades(String teades) {
        this.teades = teades;
    }

    
    @Column(name="teadef", nullable=false)
    public short getTeadef() {
        return this.teadef;
    }
    
    public void setTeadef(short teadef) {
        this.teadef = teadef;
    }




}


