package org.cargo.bl.jpa;
// Generated 23-abr-2016 18:56:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Teo generated by hbm2java
 */
@Entity
@Table(name="teo"
    ,catalog="cargo"
)
public class Teo  implements java.io.Serializable {


     private String teocod;
     private long version;
     private String teodes;
     private short teodef;
     private Set<Tta> ttas = new HashSet<Tta>(0);
     private Set<Tca> tcas = new HashSet<Tca>(0);

    public Teo() {
    }

	
    public Teo(String teocod, String teodes, short teodef) {
        this.teocod = teocod;
        this.teodes = teodes;
        this.teodef = teodef;
    }
    public Teo(String teocod, String teodes, short teodef, Set<Tta> ttas, Set<Tca> tcas) {
       this.teocod = teocod;
       this.teodes = teodes;
       this.teodef = teodef;
       this.ttas = ttas;
       this.tcas = tcas;
    }
   
     @Id 

    
    @Column(name="teocod", unique=true, nullable=false, length=5)
    public String getTeocod() {
        return this.teocod;
    }
    
    public void setTeocod(String teocod) {
        this.teocod = teocod;
    }

    @Version
    @Column(name="version", nullable=false)
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }

    
    @Column(name="teodes", nullable=false, length=80)
    public String getTeodes() {
        return this.teodes;
    }
    
    public void setTeodes(String teodes) {
        this.teodes = teodes;
    }

    
    @Column(name="teodef", nullable=false)
    public short getTeodef() {
        return this.teodef;
    }
    
    public void setTeodef(short teodef) {
        this.teodef = teodef;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="teo")
    public Set<Tta> getTtas() {
        return this.ttas;
    }
    
    public void setTtas(Set<Tta> ttas) {
        this.ttas = ttas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="teo")
    public Set<Tca> getTcas() {
        return this.tcas;
    }
    
    public void setTcas(Set<Tca> tcas) {
        this.tcas = tcas;
    }




}


