package org.cargo.bl.jpa;
// Generated 23-abr-2016 18:56:39 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Tta generated by hbm2java
 */
@Entity
@Table(name="tta"
    ,catalog="cargo"
)
public class Tta  implements java.io.Serializable {


     private long ttacod;
     private long version;
     private Cyp cyp;
     private Teo teo;
     private String ttaloc;
     private String ttacypraz;
     private String ttacypidf;
     private String ttacyptkr;

    public Tta() {
    }

    public Tta(long ttacod, Cyp cyp, Teo teo, String ttaloc, String ttacypraz, String ttacypidf, String ttacyptkr) {
       this.ttacod = ttacod;
       this.cyp = cyp;
       this.teo = teo;
       this.ttaloc = ttaloc;
       this.ttacypraz = ttacypraz;
       this.ttacypidf = ttacypidf;
       this.ttacyptkr = ttacyptkr;
    }
   
     @Id 

    
    @Column(name="ttacod", unique=true, nullable=false)
    public long getTtacod() {
        return this.ttacod;
    }
    
    public void setTtacod(long ttacod) {
        this.ttacod = ttacod;
    }

    @Version
    @Column(name="version", nullable=false)
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ttacypcod", nullable=false)
    public Cyp getCyp() {
        return this.cyp;
    }
    
    public void setCyp(Cyp cyp) {
        this.cyp = cyp;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ttateocod", nullable=false)
    public Teo getTeo() {
        return this.teo;
    }
    
    public void setTeo(Teo teo) {
        this.teo = teo;
    }

    
    @Column(name="ttaloc", nullable=false, length=20)
    public String getTtaloc() {
        return this.ttaloc;
    }
    
    public void setTtaloc(String ttaloc) {
        this.ttaloc = ttaloc;
    }

    
    @Column(name="ttacypraz", nullable=false, length=80)
    public String getTtacypraz() {
        return this.ttacypraz;
    }
    
    public void setTtacypraz(String ttacypraz) {
        this.ttacypraz = ttacypraz;
    }

    
    @Column(name="ttacypidf", nullable=false, length=20)
    public String getTtacypidf() {
        return this.ttacypidf;
    }
    
    public void setTtacypidf(String ttacypidf) {
        this.ttacypidf = ttacypidf;
    }

    
    @Column(name="ttacyptkr", nullable=false, length=5)
    public String getTtacyptkr() {
        return this.ttacyptkr;
    }
    
    public void setTtacyptkr(String ttacyptkr) {
        this.ttacyptkr = ttacyptkr;
    }




}


