package org.cargo.bl.jpa;
// Generated 23-abr-2016 20:32:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Tta generated by hbm2java
 */
@Entity
@Table(name="tta"
    ,catalog="cargo"
)
public class Tta  implements java.io.Serializable {


     private long ttacod;
     private long version;
     private Pro pro;
     private Teo teo;
     private String ttaloc;
     private String ttaproraz;
     private String ttaproidf;
     private String ttaprotkr;

    public Tta() {
    }

    public Tta(long ttacod, Pro pro, Teo teo, String ttaloc, String ttaproraz, String ttaproidf, String ttaprotkr) {
       this.ttacod = ttacod;
       this.pro = pro;
       this.teo = teo;
       this.ttaloc = ttaloc;
       this.ttaproraz = ttaproraz;
       this.ttaproidf = ttaproidf;
       this.ttaprotkr = ttaprotkr;
    }
   
     @Id 

    
    @Column(name="ttacod", unique=true, nullable=false)
    public long getTtacod() {
        return this.ttacod;
    }
    
    public void setTtacod(long ttacod) {
        this.ttacod = ttacod;
    }

    @Version
    @Column(name="version", nullable=false)
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ttaprocod", nullable=false)
    public Pro getPro() {
        return this.pro;
    }
    
    public void setPro(Pro pro) {
        this.pro = pro;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ttateocod", nullable=false)
    public Teo getTeo() {
        return this.teo;
    }
    
    public void setTeo(Teo teo) {
        this.teo = teo;
    }

    
    @Column(name="ttaloc", nullable=false, length=20)
    public String getTtaloc() {
        return this.ttaloc;
    }
    
    public void setTtaloc(String ttaloc) {
        this.ttaloc = ttaloc;
    }

    
    @Column(name="ttaproraz", nullable=false, length=80)
    public String getTtaproraz() {
        return this.ttaproraz;
    }
    
    public void setTtaproraz(String ttaproraz) {
        this.ttaproraz = ttaproraz;
    }

    
    @Column(name="ttaproidf", nullable=false, length=20)
    public String getTtaproidf() {
        return this.ttaproidf;
    }
    
    public void setTtaproidf(String ttaproidf) {
        this.ttaproidf = ttaproidf;
    }

    
    @Column(name="ttaprotkr", nullable=false, length=5)
    public String getTtaprotkr() {
        return this.ttaprotkr;
    }
    
    public void setTtaprotkr(String ttaprotkr) {
        this.ttaprotkr = ttaprotkr;
    }




}


